languageCode = "en-US"
layoutdir = "layouts"
publishdir = "docs"
baseurl = "http://dat.works/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Dat Nguyen"
  title = "Dat Nguyen's Resume"
  description = "Dat Resume"
  intro = "Trying to make the world a better place. One line of code at a time!"
  avatar = "profile.jpeg"
  email = "hi@dat.works"
  github = "datlife"
  twitter = "datfreedom"


  # Custom assets can be linked with their paths relative to static/
  custom_css = []
